project_id = "rmnllpfeapndymmsqsnc"

[functions.shiprocket-create-session]
verify_jwt = true

[functions.shiprocket-test-payment]
verify_jwt = false

[functions.shiprocket-webhook]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.admin-verify]
verify_jwt = false

[functions.admin-keys]
verify_jwt = false
