project_id = "rmnllpfeapndymmsqsnc"

[functions.shiprocket-check-serviceability]
verify_jwt = true

[functions.shiprocket-create-shipment]
verify_jwt = true

[functions.shiprocket-create-session]
verify_jwt = true

[functions.shiprocket-test-payment]
verify_jwt = false

[functions.shiprocket-webhook]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.admin-verify]
verify_jwt = false

[functions.admin-keys]
verify_jwt = false

[functions.shiprocket-catalog-products]
verify_jwt = false

[functions.shiprocket-catalog-products-by-collection]
verify_jwt = false

[functions.shiprocket-catalog-collections]
verify_jwt = false

[functions.shiprocket-sync-product]
verify_jwt = true

[functions.shiprocket-sync-collection]
verify_jwt = true

[functions.shiprocket-order-details]
verify_jwt = true
